protected/modules/admin/controllers/AuthController.php
<?php

class AuthController extends CController
{
	public $layout = 'columnx';
	
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('login'),
				'users'=>array('*'),
			)
		);	
	}
	
	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		if(Yii::app()->user->checkAccess('superadmin'))
		{
			$this->redirect(array('/admin/dashboard/index'));
		}
		
		$model=new LoginForm;
	
		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	
		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
			{
				$this->redirect(array('/admin/dashboard/index'));
			}
		}
		
		// display the login form
		$this->render('login',array('model'=>$model));
	}
	
	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout(false);
        $this->redirect(array('/admin/auth/login'));	
	}
	
    public function actionRegister()
    {
    
    }
    
    public function actionUnauthorized()
    {
    	$this->render('not-authorized');
    }
}

protected/modules/admin/controllers/PartnerController.php
<?php

class PartnerController extends AdminController
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model = Partner::model()->with('vendors')->find('t.user_id=:user_id', array(':user_id'=>$id));
		$this->render('view',array(
			'model'=>$model,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionNew()
	{
		$model=new Partner;
		$userModel = new User;
		
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$userModel->attributes=$_POST['User'];
			$criteria = new CDbCriteria;
			$criteria->condition = "status_type = 'user' AND status = 'unverified'";
			$status = Status::model()->find($criteria);
			$userModel->status_id = $status->id;
				
			$model->attributes=$_POST['Partner'];
			$transaction = Yii::app()->db->beginTransaction();
				
			if($userModel->save())
			{
				$model->user_id = $userModel->getPrimaryKey();
				
				if($model->save()) 
				{
					$transaction->commit();
					Yii::app()->user->setFlash('success','Partner has been saved');
					$this->redirect(array('index'));
				}
				else
				{
					$transaction->rollback();
				}
			}
		}

		//Formatter::arrayFormat($model->getErrors());
		$this->render('create',array(
			'model'=>$model,
			'userModel'=>$userModel
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Partner']))
		{
			$model->attributes=$_POST['Partner'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->user_id));
		}
 
		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$partners = Partner::model()->with('vendor_count')->findAll();

		$this->render('index', array('partners'=>$partners));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Partner('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Partner']))
			$model->attributes=$_GET['Partner'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Partner the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Partner::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Partner $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='partner-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/admin/controllers/ProductController.php
<?php

class ProductController extends AdminController
{
	/**
	 * Index method
	 */
	public function actionIndex()
	{
		$products = Product::model()->with('productType')->findAll();
		$this->render('index', array('products'=>$products));
	}

	/**
	 * Add a new product lot
	 */
	public function actionNewLot()
	{
		$model = new ProductLot;
		
		if(isset($_POST['ProductLot']))
		{
			$model->attributes = $_POST['ProductLot'];
			if($model->save())
			{
				Yii::app()->user->setFlash('success',' Product Lot have been saved');
				$this->redirect(array('index'));
			}
		}
		
		$this->render('create-lot', array('model'=>$model));
	}
	
	/**
	 * Add a new product
	 */
	public function actionNewProduct()
	{
		$model = new Product();
		if(isset($_POST['Product']))
		{
			$model->attributes = $_POST['Product'];
			$transaction = Yii::app()->db->beginTransaction();
			
			//Handle uploaded image file
			$rnd = rand(0,9999);
			$uploadedFile = CUploadedFile::getInstance($model,'image');
			$imageAttributes = getimagesize($uploadedFile->tempName);
			$width = $imageAttributes[0];	// first element is width of image
			$height = $imageAttributes[1];	// second element is height;
			
			//We would accept only a fixed dimension for images
			if($width!="300" && $height!="200")
			{
				Yii::app()->user->setFlash('error',' The image is not of appropriate width and height');
				$this->render('create-product', array('model'=>$model));
				return;
			}
			
			$filename = "{$rnd}-{$uploadedFile}";
			$model->image = $filename;

			if($model->save())
			{
				$uploadedFile->saveAs(Yii::app()->basepath.Yii::app()->params['productImagePath'].$filename);

				$transaction->commit();
					
				Yii::app()->user->setFlash('success',' Product has been saved');
				$this->redirect(array('index'));
			}
		}
		
		$this->render('create-product', array('model'=>$model));
	}
	
	public function actionUpdate($id)
	{
		$model = Product::model()->findByPk($id);
		if(isset($_POST['Product']))
		{
			$model->attributes = $_POST['Product'];
			$transaction = Yii::app()->db->beginTransaction();
				
			//Handle uploaded image file
			$rnd = rand(0,9999);
			$uploadedFile = CUploadedFile::getInstance($model,'image');
			$imageAttributes = getimagesize($uploadedFile->tempName);
			$width = $imageAttributes[0];	// first element is width of image
			$height = $imageAttributes[1];	// second element is height;
				
			//We would accept only a fixed dimension for images
			if($width!="300" && $height!="200")
			{
				Yii::app()->user->setFlash('error',' The image is not of appropriate width and height');
				$this->render('create-product', array('model'=>$model));
				return;
			}
				
			$filename = "{$rnd}-{$uploadedFile}";
			$model->image = $filename;
		
			if($model->save())
			{
				$uploadedFile->saveAs(Yii::app()->basepath.Yii::app()->params['productImagePath'].$filename);
		
				$transaction->commit();
					
				Yii::app()->user->setFlash('success',' Product has been saved');
				$this->redirect(array('index'));
			}
		}
		
		$this->render('create-product', array('model'=>$model));
	}
	
	public function actionNewType()
	{
		$model = new ProductType;
		$this->render('create-type', array('model'=>$model));
	}
	
	public function actionView()
	{
		$this->render('view');	
	}
	
	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}

protected/modules/admin/controllers/VendorController.php
<?php

class VendorController extends AdminController
{
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model = Vendor::model()->with('productLots')->find('t.user_id=:user_id', array(':user_id'=>$id));
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionNew()
	{
		$model=new Vendor;
		$userModel = new User;
		
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		
		if(isset($_POST['User']) && isset($_POST['Vendor']))
		{
			$userModel->attributes = $_POST['User'];
			$userModel->username = $this->genRandomString(10);
			$userModel->password = $userModel->password_repeat = 'ligaia';
			
			/* Get the status */
			$criteria = new CDbCriteria;
			$criteria->condition = "status_type = 'user' AND status = 'inactive'";
			$status = Status::model()->find($criteria);
			$userModel->status_id = $status->id;
			
			$transaction = Yii::app()->db->beginTransaction();
			
			//Formatter::arrayFormat($userModel); exit;
			if($userModel->save())
			{
				$model->attributes=$_POST['Vendor'];
				$model->user_id = $userModel->getPrimaryKey();

				if($model->save())
				{
					$transaction->commit();
					$this->redirect(array('view','id'=>$model->user_id));
				}
				else
				{
					//Formatter::arrayFormat($model->getErrors());
					$transaction->rollback();
				}
			}
			
			//Formatter::arrayFormat($userModel->getErrors());
		}

		$this->render('create',array(
			'model'=>$model,
			'userModel'=>$userModel
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Vendor']))
		{
			$model->attributes=$_POST['Vendor'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->user_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Vendor',
				array(
					'criteria'=>array(
						'with'=>array(
							'partner'
						)
					)
				)
			);
		$this->render('index',array(
			'vendors'=>$dataProvider->GetData(),
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Vendor('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Vendor']))
			$model->attributes=$_GET['Vendor'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	protected function genRandomString($length=10, $chars='', $type=array()) {
		//initialize the characters
		$alphaSmall = 'abcdefghijklmnopqrstuvwxyz';
		$alphaBig = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
		$num = '0123456789';
		$othr = '`~!@#$%^&*()/*-+_=[{}]|;:",<>.\/?' . "'";
	
		$characters = "";
		$string = '';
		//defaults the array values if not set
		isset($type['alphaSmall']) ? $type['alphaSmall']: $type['alphaSmall'] = true; //alphaSmall - default true
		isset($type['alphaBig']) ? $type['alphaBig']: $type['alphaBig'] = true; //alphaBig - default true
		isset($type['num']) ? $type['num']: $type['num'] = true; //num - default true
		isset($type['othr']) ? $type['othr']: $type['othr'] = false; //othr - default false
		isset($type['duplicate']) ? $type['duplicate']: $type['duplicate'] = true; //duplicate - default true
	
		if (strlen(trim($chars)) == 0) {
			$type['alphaSmall'] ? $characters .= $alphaSmall : $characters = $characters;
			$type['alphaBig'] ? $characters .= $alphaBig : $characters = $characters;
			$type['num'] ? $characters .= $num : $characters = $characters;
			$type['othr'] ? $characters .= $othr : $characters = $characters;
		}
		else
			$characters = str_replace(' ', '', $chars);
	
		if($type['duplicate'])
		for (; $length > 0 && strlen($characters) > 0; $length--) {
			$ctr = mt_rand(0, (strlen($characters)) - 1);
			$string .= $characters[$ctr];
		}
		else
			$string = substr (str_shuffle($characters), 0, $length);
	
		return $string;
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Vendor the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Vendor::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Vendor $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='vendor-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/admin/views/layouts/columnx.php
<?php $this->beginContent('/layouts/admin'); ?>
	<?php echo $content; ?>
<?php $this->endContent(); ?>

protected/modules/admin/views/layouts/old_admin.php
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7 sidebar sidebar-fusion sidebar-kis footer-sticky navbar-sticky"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8 sidebar sidebar-fusion sidebar-kis footer-sticky navbar-sticky"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9 sidebar sidebar-fusion sidebar-kis footer-sticky navbar-sticky"> <![endif]-->
<!--[if gt IE 8]> <html class="ie sidebar sidebar-fusion sidebar-kis footer-sticky navbar-sticky"> <![endif]-->
<!--[if !IE]><!-->
<html class="app sidebar sidebar-fusion sidebar-kis footer-sticky navbar-sticky">
<!-- <![endif]-->
<head>
<title><?php echo CHtml::encode($this->
pageTitle); ?></title>
<!-- Meta -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
<!-- 
	**********************************************************
	In development, use the LESS files and the less.js compiler
	instead of the minified CSS loaded by default.
	**********************************************************
	<link rel="stylesheet/less" href="<?php echo yii::app()->request->baseUrl ?>/coral/assets/less/admin/module.admin.stylesheet-complete.sidebar_type.fusion.less" />
	-->
<!--[if lt IE 9]><link rel="stylesheet" href="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/library/bootstrap/css/bootstrap.min.css" /><![endif]-->
<link rel="stylesheet" href="<?php echo yii::app()->
request->baseUrl ?>/coral/assets/css/admin/module.admin.stylesheet-complete.sidebar_type.fusion.min.css" /> 
<link rel="stylesheet" href="<?php echo $this->module->assetsUrl?>/css/admin.css" /> 
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/library/jquery/jquery.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/library/jquery/jquery-migrate.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/library/modernizr/modernizr.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/plugins/less-js/less.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/modules/admin/charts/flot/assets/lib/excanvas.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/plugins/browser/ie/ie.prototype.polyfill.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/library/jquery-ui/js/jquery-ui.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/plugins/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->module->assetsUrl?>/js/admin.js""></script>
<script>if (/*@cc_on!@*/false && document.documentMode === 10) { document.documentElement.className+=' ie ie10'; }</script>
</head>
<body class=" menu-right-hidden">
<!-- Main Container Fluid -->
<div class="container-fluid menu-hidden">
	<!-- Main Sidebar Menu -->
	<div id="menu" class="hidden-print hidden-xs sidebar-blue sidebar-brand-primary">
		<div id="sidebar-fusion-wrapper">
			<div id="brandWrapper">
				<a href="index.html?lang=en" class="display-block-inline pull-left logo"><img src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/images/logo/app-logo-style-default.png" alt=""></a>
				<a href="index.html?lang=en"><span class="text">Ligaia</span></a>
			</div>
			<?php 
			
			$this->widget('SideMenu', array(
			    'items'=>array(
			        // Important: you need to specify url as 'controller/action',
			        // not just as 'controller' even if default acion is used.
			        array('label'=>'Partners', 'url'=>'#partners', 'items'=>array(
						array('label'=>'List Partners', 'url'=>array('partner/index'), 'active'=>$this->uniqueid=='admin/partner' && $this->action->Id=='index'),
						array('label'=>'Add Partner', 'url'=>array('partner/create'), 'active'=>$this->uniqueid=='admin/partner' && $this->action->Id=='create'),
						),
						'linkOptions'=>array('data-toggle'=>'collapse', 'class'=>$this->uniqueid=='admin/partner'? 'collapsed': ''),
						'submenuOptions'=>array('id'=>'partners','class'=>$this->uniqueid=='admin/partner'? 'collapse in': 'collapse'),
						'active'=>$this->uniqueid=='admin/partner'
					),
			        // 'Products' menu item will be selected no matter which tag parameter value is since it's not specified.
			        array('label'=>'Vendors', 'url'=>'#vendors', 'items'=>array(
						array('label'=>'List Vendors', 'url'=>array('vendor/index'), 'active'=>$this->uniqueid=='admin/vendor' && $this->action->Id=='index'),
			            array('label'=>'Add Vendor', 'url'=>array('vendor/create'), 'active'=>$this->uniqueid=='admin/vendor' && $this->action->Id=='create'),
			        	),
						'linkOptions'=>array('data-toggle'=>'collapse', 'class'=>$this->uniqueid == 'admin/vendor'? 'collapsed': ''),
						'submenuOptions'=>array('id'=>'vendors', 'class'=>$this->uniqueid == 'admin/vendor'? 'collapse in': 'collapse'),
						'active'=>$this->uniqueid=='admin/vendor'
					),
					array('label'=>'Products', 'url'=>'#products', 'items'=>array(
						array('label'=>'List Products', 'url'=>array('product/index'), 'active'=>$this->uniqueid=='admin/product' && $this->action->Id=='index'),
						array('label'=>'Add Product', 'url'=>array('product/newProduct'), 'active'=>$this->uniqueid=='admin/product' && $this->action->Id=='newProduct'),
						array('label'=>'Add Product Variation', 'url'=>array('product/newVariant'), 'active'=>$this->uniqueid=='admin/product' && $this->action->Id=='newVariant'),
						array('label'=>'Add Product Lot', 'url'=>array('product/newLot'), 'active'=>$this->uniqueid=='admin/product' && $this->action->Id=='newLot'),
						),
						'linkOptions'=>array('data-toggle'=>'collapse', 'class'=>$this->uniqueid=='admin/product'? 'collapsed': ''),
						'submenuOptions'=>array('id'=>'products', 'class'=>$this->uniqueid=='admin/product'? 'collapse in': 'collapse'),
						'active'=>$this->uniqueid=='admin/product'
					),
			    ),
				'id'=>'mainNavigation',
				'activeCssClass'=>'active',
				'htmlOptions'=>array('class'=>'menu list-unstyled'),
				'itemCssClass'=>'hasSubmenu',
			));
			?>
		</div>
	</div>
	<!-- // Main Sidebar Menu END -->
	<!-- Content -->
	<div id="content">
		<div class="navbar hidden-print navbar-primary main" role="navigation">
			<div class="user-action user-action-btn-navbar pull-left border-right">
				<button class="btn btn-sm btn-navbar btn-primary btn-stroke"><i class="fa fa-bars fa-2x"></i></button>
			</div>
			<div class="user-action visible-xs user-action-btn-navbar pull-right">
				<button class="btn btn-sm btn-navbar-right btn-primary"><i class="fa fa-fw fa-arrow-right"></i><span class="menu-left-hidden-xs"> Modules</span></button>
			</div>
			<div class="user-action pull-right menu-right-hidden-xs menu-left-hidden-xs">
				<div class="dropdown username hidden-xs pull-left">
					<a class="dropdown-toggle " data-toggle="dropdown" href="#">
					<?php echo Yii::app()->user->username?> <span class="caret"></span>
					</a>
					<ul class="dropdown-menu pull-right">
						<li><a href="social_account.html?lang=en">Settings</a></li>
						<li><?php echo CHtml::link('Logout',array('auth/logout')); ?></li>
					</ul>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="layout-app" style="visibility: visible;">
			<!-- row-app -->
			<div class="row row-app lg-app">
				<!-- col -->
				<?php echo $content ?>
			</div>
		</div>
	</div>
	<!-- // Content END -->
	<div class="clearfix">
	</div>
	<!-- // Sidebar menu & content wrapper END -->
	<!-- Footer -->
	<div id="footer" class="hidden-print">
		<!--  Copyright Line -->
		<div class="copy">
			&copy; 2014 - <a href="http://ligaia.com">Ligaia</a> - All Rights Reserved.
		</div>
		<!--  End Copyright Line -->
	</div>
	<!-- // Footer END -->
</div>
<!-- // Main Container Fluid END -->
<!-- Global -->
<script data-id="App.Config">
	var basePath = '',
		commonPath = '<?php echo yii::app()->request->baseUrl ?>/coral/assets/',
		rootPath = '../',
		DEV = false,
		componentsPath = '<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/',
		layoutApp = false,
		module = 'admin';
	var primaryColor = '#eb6a5a',
		dangerColor = '#b55151',
		successColor = '#609450',
		infoColor = '#4a8bc2',
		warningColor = '#ab7a4b',
		inverseColor = '#45484d';
	var themerPrimaryColor = primaryColor;
	</script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/library/bootstrap/js/bootstrap.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/plugins/nicescroll/jquery.nicescroll.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/plugins/breakpoints/breakpoints.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/common/tables/datatables/assets/lib/js/jquery.dataTables.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/common/tables/datatables/assets/custom/js/DT_bootstrap.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/common/tables/datatables/assets/custom/js/datatables.init.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/common/forms/elements/fuelux-checkbox/fuelux-checkbox.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/common/forms/elements/bootstrap-select/assets/lib/js/bootstrap-select.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/common/forms/elements/bootstrap-select/assets/custom/js/bootstrap-select.init.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/common/tables/datatables/assets/lib/extras/FixedHeader/FixedHeader.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/common/tables/datatables/assets/lib/extras/ColReorder/media/js/ColReorder.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/common/tables/classic/assets/js/tables-classic.init.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/core/js/sidebar.main.init.js?v=v1.9.6"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/core/js/sidebar.collapse.init.js?v=v1.9.6"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/core/js/core.init.js?v=v1.9.6"></script>
<script src="<?php echo yii::app()->request->baseUrl ?>/coral/assets/components/core/js/animations.init.js?v=v1.9.6"></script>
</body>
</html>